sonar.projectKey=BraCR10_PoC-QA
sonar.organization=bracr10
sonar.projectName=PoC-QA
sonar.projectVersion=1.0
sonar.sources=smart_lock
sonar.sourceEncoding=UTF-8
sonar.cfamily.build-wrapper-output=build/bw-output
